#!/usr/bin/env bash

# WORKAROUND for glibc 2.33 and old Docker
# Thanks to https://github.com/lxqt/lxqt-panel/pull/1562
patched_glibc=glibc-linux4-2.33-4-x86_64.pkg.tar.zst &&
    curl -LO --silent "https://repo.archlinuxcn.org/x86_64/$patched_glibc" &&
    bsdtar -C / -xf "$patched_glibc"
