#!/usr/bin/env bash

#############################
#    Kernel Build Script    #
#############################

# Set defaults
wd=$(pwd)
out=$wd/out
BUILD="/home/theradcolor/kernel/source"
ANYKERNEL_DIR=${HOME}/anykernel2
DATE=$(date +"%d-%m-%y")
BUILD_START=$(date +"%s")

# Define colors
green='\e[0;32m'
white='\033[0m'

echo -e "*****************************************************"
echo "                      Compile kernel                    "
echo -e "*****************************************************"

# Set kernel source workspace
cd ${BUILD} || exit

# Use ccache
export USE_CCACHE=1
export CCACHE_DIR="/home/theradcolor/.ccache"

# Export ARCH <arm, arm64, x86, x86_64>
export ARCH=arm64
export SUBARCH=arm64

# Set kernal configurations
export LOCALVERSION=-v1
export KBUILD_BUILD_USER=theradcolor
export KBUILD_BUILD_HOST=ILLYRIA

# Compiler String
GCC64=/home/theradcolor/whyred/compilers/aarch64-linux-android-4.9/bin/aarch64-linux-android-
GCC32=/home/theradcolor/whyred/compilers/arm-linux-androideabi-4.9/bin/arm-linux-androideabi-

# Make and Clean
make O="$out" clean
make O="$out" mrproper

# Make <defconfig>
make O="$out" ARCH=arm64 device_defconfig

# Build Kernel
make O="$out" \
    CROSS_COMPILE="${GCC64}" \
    CROSS_COMPILE_ARM32="${GCC32}" \
    -j6 2>&1 | tee "$out"/kernel.log

BUILD_END=$(date +"%s")
DIFF=$("$BUILD_END" - "$BUILD_START")
echo -e "$green" "Build completed in $($DIFF / 60) minute(s) and $($DIFF % 60) seconds." "$white"

echo -e "Making Flashable Template using anykernel2"

# Clean anykernel2 directory
rm -f "$ANYKERNEL_DIR"/Image.gz*
rm -f "$ANYKERNEL_DIR"/zImage*
rm -f "$ANYKERNEL_DIR"/dtb*

# Change the directory to anykernel2 directory
cd "$ANYKERNEL_DIR" || exit
#remove all zips
rm ./*.zip

# Copy thhe image.gz-dtb to anykernel2 directory
cp "$out"/arch/arm64/boot/Image.gz-dtb "$ANYKERNEL_DIR"/

#Build a flashable zip Device using anykernel2
zip -r9 kernel-"$DATE".zip ./* -x README .git
